// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	channel "perun.network/go-perun/channel"

	testing "testing"
)

// AdjudicatorSubscription is an autogenerated mock type for the AdjudicatorSubscription type
type AdjudicatorSubscription struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *AdjudicatorSubscription) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Err provides a mock function with given fields:
func (_m *AdjudicatorSubscription) Err() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Next provides a mock function with given fields:
func (_m *AdjudicatorSubscription) Next() channel.AdjudicatorEvent {
	ret := _m.Called()

	var r0 channel.AdjudicatorEvent
	if rf, ok := ret.Get(0).(func() channel.AdjudicatorEvent); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(channel.AdjudicatorEvent)
		}
	}

	return r0
}

// NewAdjudicatorSubscription creates a new instance of AdjudicatorSubscription. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewAdjudicatorSubscription(t testing.TB) *AdjudicatorSubscription {
	mock := &AdjudicatorSubscription{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
